apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vips.ipam.citrix.com
spec:
  group: ipam.citrix.com
  version: v1
  names:
    kind: Vip
    plural: vips
    singular: vip
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            ipaddress:
              type: string
            service:
              type: string
            description:
              type: string
