---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netscaler-lbc
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netscaler-lbc
rules:
- apiGroups: [""]
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ipam.citrix.com
  resources:
  - vips
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netscaler-lbc
subjects:
- kind: ServiceAccount
  name: netscaler-lbc
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: netscaler-lbc
